name: flutter_notification
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2

  firebase_core: ^2.11.0
  awesome_notifications: ^0.7.4+1
  awesome_notifications_fcm: ^0.7.4+1

  logger: 1.1.0

  fluttertoast: ^8.2.1

  googleapis_auth: ^1.3.1
  dio: ^5.0.1

  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  injectable: 1.5.3

  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.1.0+1
  injectable_generator: ^1.5.3
  hive_generator: ^1.1.2
  import_sorter: ^4.6.0
  flutter_lints: 2.0.1
  change_app_package_name: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

